### ISSUE TITLE
File [umenu] should also only show filename when opening a single file + make nice popup fullpath hint

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#37]
It does so when opening a folder. There is only a limited space for the filename in the UI, BUT what we can do is to manipulate the hint of the [umenu] based on the selected file + its folder as a prefix: so that on mouse hover the user will see the full path.

**Comment by aleksati** [comment]
Hey! I had some time left over tonight so I went ahead and made something that can work here. Check it out when you can, and feel free to edit if you had another plan or solution in mind for this :)

It required a little more work than first expected. When I changed the filename sent to the umenu from the [open-file] it naturally affected the outputted info FROM the umenu which, in turn, affected where the exported files were rendered to (usually straight to desktop instead of the folder where the videoes were). 

Anyway, the fix is located in the elegantly named subpatch [p reassembling-file-and-folder-names] + some configurations to the [p open-file] and [p open-folder].

**Comment by balintlaczko** [comment]
Oh I just finished implementing the same thing... :D

**Comment by balintlaczko** [comment]
I get 2 error messages when the patch loads now: ""$" variable out of range (1)" and ""$" variable out of range (2)". I think it would also be nice to see the full path (not just the path to the file) in case we load a folder, it might be a bit more consistent behavior for the popup hint. Otherwise it's good! I discard my implementation.

But please, in the future just let me know in advance if you plan to work on an issue I created and assigned to myself so it's only one of us taking the time to do it. :)

**Comment by aleksati** [comment]
Haha, absolutely! Sorry about that. Thought I was the only one nerding on a Sunday night. I guess I was wrong! I think I made a hint for the folder as well, but I guess it only shows the path to the folder and not the file in the folder?

**Comment by balintlaczko** [comment]
Don't worry, only ask me if you see that I assigned myself on it already, that means I am working on it.

For me it looks like if I load a file, the hint shows the full path (path to file + file), and if I load the folder the hint shows only the path to file (without the file). I can imagine that this makes more sense to someone, so it is a matter of taste, but my 2 cents is just that it is good that a feature always does the same thing, just to stay consistent.

**Comment by aleksati** [comment]
This is now implemented.
