### ISSUE TITLE
Is there any reason to gate the incoming signals to the mavg, avg and motiongrams?

### ISSUE THREAD

**Issue by aleksati** [balintlaczko/VideoAnalysis#47]
What matters is if they export or not. So the gates (controlled by the boxes is in the UI) should be located between [p create-file-name] and the matrices. 

Correct me if I'm wrong here! Or if I´m somehow missing something.

**Comment by AleksanderTidemann** [comment]
Actually. Maybe we can gate all the analysis (mg, avg, mavg and analysis) when doing online playback. Might have some positive effect on the CPU?

**Comment by balintlaczko** [comment]
Indeed, the gates are important to cut all the processing below them when we don't need it. Also, it should depend on the framedump rather than whether the export image toggle is checked, since we only need it offline.

**Comment by aleksati** [comment]
Noted! but might be good to have some processing in real-time? check out my issue #50.

**Comment by balintlaczko** [comment]
btw I am actually thinking about wrapping the different modules into [poly~]-s which would make the program use more than 1 cpu cores, and also it would make our dev life easier, since if you change something in module A it does not conflict with my change in module B. I will open an issue for this.

**Comment by aleksati** [comment]
Ok, would we need the gates which "depend on the framedump rather than whether the export image toggle is checked" if wrap them in [poly]? If not then I won't bother with this now.

**Comment by balintlaczko** [comment]
I think the issues are not strictly related, we can wrap the modules into [poly~]-s without changing the logic inside, and also all the send-receive communication can stay, but the gate behavior should be fixed in any case if you ask me, just so that we can be sure that it only consumes cpu when we actually want to use the thing. It's not a pressing thing, but should be done eventually.

**Comment by aleksati** [comment]
Okey, cool. I can make these minor changes to the gates tomorrow!

**Comment by aleksati** [comment]
These "two-factor-authentication gates" are now implemented for avg image, mavg images and the motiongrams.
