### ISSUE TITLE
some random weird problems when batch exporting - sometimes

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#59]
typically:
- black images (not all)
- inadequate cropping
- the cv.jit.mean bug from #53 

We should look carefully into what exactly happens in the batch processing when finish a video and start the next one.

**Comment by aleksati** [comment]
About the cropping:

Seems like the issue here is that when exporting, the [umenu], and menu item bang, has higher priority than Read, Framecount, and moviedim etc. from the jit.movie. This means that the correct moviedim doesn't get "updated" in the [crop-coll] before framedumping the video. A solution to this should be to store the moviedims from the start, in a [coll] possibly, and call them from the menu item "bang" at the beginning of every framedump.

I will try and make something for this.

**Comment by balintlaczko** [comment]
OK, that seems like good to have anyway. For the scheduling problem, have you considered using [defer] or [deferlow]? I think during an "offline" render nothing should be in the scheduler thread. I don't even know how [umenu] got there, but it most certainly shouldn't have. Will take a look too!
