### ISSUE TITLE
motiongrams' dim should take trimming into account

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#89]
It still has the full framecount as width or height.

**Comment by aleksati** [comment]
It should also effect the value of the Processed frames.

**Comment by aleksati** [comment]
I implemented this now. I made it so that the Exported Motiongrams, Motiongram UI dims and the Motiongram preview all "listen" to the total amount of Processed Frames instead of the framecount. The processed frames are now scaled based on the loop-points and skipframe value. I think this is a nice way of doing it since now we always bang trimming and skipframe values when loading a new item in the umenu. 

However, now, when changing the item in the umenu to a video that has both skipframe and trimming, the processed-frame count gets two values in quick succession. It works fine but its not the most elegant way of doing it. It does this because the processed framecount has to change in realtime if the user interacts with either the skipframe or the loop-points. Therefore, since these values have to be divided by one another to get the processed framecount, it gets two values in quick succession when changing to an item with both skipframe and trimming.

There are ways to avoid this, like maybe having two processed framecount paths (one for the UI and one for the system based on the framedump or something), but I didn't want to change too much of our patch if it's not necessary.

Anyways, have a quick look in the [p processed-frames] subpatch in the main patcher when you can,  @balintlaczko . You might know a quick fix or better way for this.

**Comment by balintlaczko** [comment]
Fixed!
