### ISSUE TITLE
history, avg, motion images don't resize/reset correctly since trimming is implemented

### ISSUE THREAD

**Issue by balintlaczko** [balintlaczko/VideoAnalysis#90]
probably they are all listening to framdump first frame. (or something else)

**Comment by aleksati** [comment]
Hey. Here are some notes after doing some more testing on the trimming function.

Framedumping with trimming:
When framedumping, the trimming starts at the correct frame but does not end at the specified frame. I did some testing and figured out that the framedump arguments work differently then we first thought.

When writing [framedump 10 30 1], for instance, the movie dumps frames from 10 to 40. and if we write [framedump 20 30 1], it dumps from 20 to 50. So the logic seems to be that the end-frame argument actually specifies how many frames to dump from the specified start-frame. So in the first example above, it dumps 30 frames from 10, resulting in frames 10 to 40 to be exported.  

[Two-factor gate]:
In this abstraction, some gates rely on "frame 1" to open the gate for the motion images and motiongrams to start writing, as you said!. So this should be changed so that it corresponds to the first frame according to the trimming value.

[mgt.write-to-file]: 
The same problem is located here. It wants the first frame to correctly start recording the Videos for export.

These last two points might also be related to the problem experienced in issue #91 . Maybe all these places which require the first frame of a framedump to perform an action should be complied and scheduled together, similar to what we did with everything that required a framedump "done" message in the main patch.

Progress bar:
Lastly, in [Only_Visible_When_Framedumping], the progress-bar also only becomes visible when it receives frame 1 of the framedump. Similarly, in [Progress-bar], we should rescale the progress bars high-low values according to the trimming.

**Comment by aleksati** [comment]
I implemented the correct framedumping method now based on the above comment. Just some changes to [p norm_time2frame] in the [p framedump] subpatch in the [VA_write_data] abstraction.

**Comment by aleksati** [comment]
Referring to my comment above, I now changed all the first frame dependencies I could find in our patch. Changes were made to:

* main patch (added and updated [p framedump scheduling] and progress-bar subpatches)
* [VA_twofactor_gate] 
* [VA write_data] 
* [VA write-to-file]
* [VA_write_general]

It seems to work just fine on my side now, but its good if double-check this. I'll do some more testing later today.

**Comment by balintlaczko** [comment]
This seems to be solved now, good job! I discovered some related problems but I'll make them into separate issues.
